
services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: airflow
      POSTGRES_PASSWORD: airflow
      POSTGRES_DB: airflow
    volumes:
      - postgres-db:/var/lib/postgresql/data
    restart: unless-stopped

  airflow-webserver:
    image: apache/airflow:2.8.1
    user: "${AIRFLOW_UID}:0"
    depends_on:
      - postgres
    env_file:
      - .env
    ports:
      - "8080:8080"
    volumes:
      - ./dags:/opt/airflow/dags
      - ./logs:/opt/airflow/logs
      - ./plugins:/opt/airflow/plugins
      - ./data:/opt/airflow/data
      - ./src:/opt/airflow/src
      - ./requirements.txt:/requirements.txt
    command: bash -c "pip install --no-cache-dir -r /requirements.txt && airflow webserver"
    restart: unless-stopped

  airflow-scheduler:
    image: apache/airflow:2.8.1
    user: "${AIRFLOW_UID}:0"
    depends_on:
      - postgres
    env_file:
      - .env
    volumes:
      - ./dags:/opt/airflow/dags
      - ./logs:/opt/airflow/logs
      - ./plugins:/opt/airflow/plugins
      - ./data:/opt/airflow/data
      - ./src:/opt/airflow/src

    command: scheduler
    restart: unless-stopped

volumes:
  postgres-db:
