
services:

  init-permissions:
    image: alpine
    user: root
    volumes:
      - ./data:/opt/airflow/data
    command: chown -R ${AIRFLOW_UID}:${AIRFLOW_UID} /opt/airflow/data

  postgres:
    image: postgres:13
    environment:
      POSTGRES_USER: airflow
      POSTGRES_PASSWORD: airflow
      POSTGRES_DB: airflow
    volumes:
      - postgres-db:/var/lib/postgresql/data
      - ./src/api/mocks:/data
    restart: unless-stopped

  airflow-webserver:
    image: apache/airflow:2.8.1
    user: "${AIRFLOW_UID}:0"
    depends_on:
      - postgres
    env_file:
      - .env
    ports:
      - "8080:8080"
    volumes:
      - ./dags:/opt/airflow/dags
      - ./logs:/opt/airflow/logs
      - ./plugins:/opt/airflow/plugins
      - ./data:/opt/airflow/data
      - ./src:/opt/airflow/src
      - ./requirements.txt:/requirements.txt
    command: bash -c "pip install --no-cache-dir -r /requirements.txt && airflow webserver"
    restart: unless-stopped

  airflow-scheduler:
    image: apache/airflow:2.8.1
    user: "${AIRFLOW_UID}:0"
    depends_on:
      - postgres
    env_file:
      - .env
    volumes:
      - ./dags:/opt/airflow/dags
      - ./logs:/opt/airflow/logs
      - ./plugins:/opt/airflow/plugins
      - ./data:/opt/airflow/data
      - ./src:/opt/airflow/src

    command: scheduler
    restart: unless-stopped

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./data/html_output:/usr/share/nginx/html:ro
    restart: unless-stopped

volumes:
  postgres-db:
