
services:

  init-permissions:
    image: alpine
    user: root
    volumes:
      - ./data:/opt/airflow/data
    command: chown -R ${AIRFLOW_UID}:${AIRFLOW_UID} /opt/airflow/data

  postgres:
    image: postgres:13
    env_file:
      - .env
    volumes:
      - postgres-db:/var/lib/postgresql/data
      - ./src/api/mocks:/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql:ro
    healthcheck:
      test: [ "CMD", "pg_isready", "-U", "airflow" ]
      interval: 5s
      retries: 10
    restart: unless-stopped

  airflow-webserver:
    build: .
    image: weather-airflow:2.8.1
    user: "${UID:-50000}:0"
    depends_on:
      postgres:
        condition: service_healthy
    env_file:
      - .env
    ports:
      - "8080:8080"
    volumes:
      - ./dags:/opt/airflow/dags
      - ./logs:/opt/airflow/logs
      - ./plugins:/opt/airflow/plugins
      - ./data:/opt/airflow/data
      - ./src:/opt/airflow/src
      - ./requirements.txt:/requirements.txt
    command: ["webserver"]
    restart: unless-stopped

  airflow-scheduler:
    image: weather-airflow:2.8.1
    user: "${UID:-50000}:0"
    depends_on:
      postgres:
        condition: service_healthy
    env_file:
      - .env
    volumes:
      - ./dags:/opt/airflow/dags
      - ./logs:/opt/airflow/logs
      - ./plugins:/opt/airflow/plugins
      - ./data:/opt/airflow/data
      - ./src:/opt/airflow/src

    command: ["scheduler"]
    restart: unless-stopped

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./data/html_output:/usr/share/nginx/html:ro
    restart: unless-stopped

volumes:
  postgres-db:
